name: pyLoad-ng
version: "1.0.5"
slug: pyload-ng
description: "The free and open-source Download Manager written in pure Python"
url: "https://github.com/tr4nt0r/pyload-ng"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl:ro
options:
  tempdir: ""
  PGID: 1000
  PUID: 1000
schema:
  PGID: int
  PUID: int
  tempdir: str?
  reset_password: bool?
  ssl: bool?
image: "ghcr.io/tr4nt0r/{arch}-pyload-ng"
panel_icon: "mdi:language-python"
ports:
  8000/tcp: 8000
  9666/tcp:
ports_description:
  8000/tcp: pyLoad Web Interface
  9666/tcp: "Click 'N' Load [default: 9666] (not supported with SSL enabled)"
webui: "[PROTO:ssl]://[HOST]:[PORT:8000]/"
