name: pyLoad-ng
version: "0.5.0b3.dev81"
slug: pyload-ng
description: "The free and open-source Download Manager written in pure Python"
url: "https://github.com/tr4nt0r/pyload-ng"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addon_config:rw
  - media:rw
  - ssl:ro
options:
  storagedir: "/media/downloads"
  tempdir: ""
schema:
  storagedir: str
  tempdir: str?
  reset_password: bool?
# image: "ghcr.io/tr4nt0r/{arch}-pyload-ng"
panel_icon: "mdi:language-python"
ports:
  8000/tcp: 8000
  9666/tcp: 9666
ports_description:
  8000/tcp: pyLoad Web Interface
  9666/tcp: "Click 'N' Load"
webui: "[PROTO:ssl]://[HOST]:[PORT:8000]/"
