# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: pyLoad-ng
version: "0.5.0b3.dev81"
slug: pyload-ng
description: "The free and open-source Download Manager written in pure Python"
url: "https://github.com/tr4nt0r/ha-pyload-ng"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addon_config:rw
  - media:rw
  - ssl:ro
options:
  storagedir: "/media/Downloads"
  tempdir: ""
schema:
  storagedir: str
  tempdir: str?
  reset_password: bool?
# image: "ghcr.io/tr4nt0r/{arch}-pyload-ng"
panel_icon: "mdi:language-python"
